### PR TITLE
Rename testcase: build.static-analysis -> scratch-build.validation

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
People seem to be universally confused about the "static-analysis" part. This is an attempt to make it things more clear so people don't need to guess as what the test actually does.

Note PRs in src.f.p.o are fine with the latest changes from Bruno. But since we'd like to show these results in Bodhi in future, and people will be able to gate on these results, I think some revamp is necessary.

**Comment by msrb** [comment]
@bgoncalv @thrix @psss any opinions? what do you guys think?

**Comment by bgoncalv** [comment]
> Note PRs in src.f.p.o are fine with the latest changes from Bruno (the description in Pagure PRs actually says "scratch build"). But since we'd like to show these results in Bodhi in future, and people will be able to gate on these results, I think some revamp is necessary.

Does bodhi show results for scratch builds?

Note that if you change test case name, you will also need to update toddlers [1], otherwise it will not be displayed on Pagure flags for PRs...

Anyway, I'm fine with the change on test case name.

[1] https://pagure.io/fedora-infra/toddlers/blob/main/f/toddlers/plugins/flag_ci_pr.py#_90

**Comment by msrb** [comment]
@bgoncalv ah, toddlers. Thanks :wink:

**Comment by msrb** [comment]
> Does bodhi show results for scratch builds?

It doesn't, but in revdeps-rebuild (don't know how to call it) cases, we report on a package which triggered the rebuild of a dependent component. And that one is a regular build, so the results should show up in Bodhi.

**Comment by bgoncalv** [comment]
> > Does bodhi show results for scratch builds?
> 
> It doesn't, but in revdeps-rebuild (don't know how to call it) cases, we report on a package which triggered the rebuild of a dependent component. And that one is a regular build, so the results should show up in Bodhi.

In that case the ci message that will be published is not this one (as the message will be from the build that triggered the scratch build) or am I missing something?

**Comment by msrb** [comment]
> In that case the ci message that will be seen in bodhi is not this one (as the message will be from the build that triggered the scratch build) or am I missing something?

It will be this one -- I added new parameter - (ARTIFACT_ID)[https://github.com/fedora-ci/dist-git-build-pipeline/blob/master/Jenkinsfile#L50]. If this is not a pull-request, the pipeline will report results for that ARTIFACT_ID, but in background it will scratch-build the dependent package.

This complicated the Jenkinsfile a bit, I will split it into two later -- one for pull requests as it was before, and one for revdeps-rebuilds.

I also need to add a README file :)

**Comment by bgoncalv** [comment]
> > In that case the ci message that will be seen in bodhi is not this one (as the message will be from the build that triggered the scratch build) or am I missing something?
> 
> It will be this one -- I added new parameter - [ARTIFACT_ID](https://github.com/fedora-ci/dist-git-build-pipeline/blob/master/Jenkinsfile#L50). If this is not a pull-request, the pipeline will report results for that ARTIFACT_ID, but in background it will scratch-build the dependent package.
> 
> This complicated the Jenkinsfile a bit, I will split it into two later -- one for pull requests as it was before, and one for revdeps-rebuilds.
> 
> I also need to add a README file :)

thanks for the clarification, no more questions :)

**Review by bgoncalv — APPROVED** [review]

**Comment by thrix** [comment]
scratch-build.validation sounds very good. +1 for making the users happy

**Review by thrix — APPROVED** [review]
LGTM

**Comment by msrb** [comment]
Thanks for the comments guys :wink: 

Let's wait for toddlers to catch up: https://pagure.io/fedora-infra/toddlers/pull-request/70#

**Comment by msrb** [comment]
Toddlers caught up, so we can merge this now.

**Pull request merged**
